/* Autori : Samuel Križan    <xkriza06>
 *          Damián Sova      <xsovad06>
 * Generated by QT Creator
*/
#include "mainwindow.h"
#include <QApplication>

int main(int argc, char *argv[]) {
    QApplication a(argc, argv);
    MainWindow w;
    w.show();
    return a.exec();
}
